# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WanHuaTong' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'AFNetworking'
    pod 'SnapKit'
    pod 'SDWebImage'
    pod 'YYModel'
  # Pods for WanHuaTong

end
